### ISSUE TITLE
open issue details occured error

### ISSUE THREAD

**Issue by archonwang** [alexwais/redmine_workflow_hidden_fields#33]
log as follow

```
Started GET "/issues/12070" for 192.168.20.253 at 2017-12-29 15:37:34 +0800
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"12070"}
  Current user: qianlan.xue (id=23)
STATEMENT 
STATEMENT (issues.status_id IN (SELECT id FROM issue_statuses WHERE is_closed=0))
  Rendered plugins/redmine_blocked_reason/app/views/issues/_action_menu.html.erb (11.2ms)
  Rendered plugins/redmine_workflow_hidden_fields/app/views/issues/show.html.erb within layouts/base (2394.1ms)
Completed 500 Internal Server Error in 3733ms (ActiveRecord: 244.9ms)


ActionView::Template::Error (undefined method `render_full_width_custom_fields_rows' for #<#<Class:0x007f741ceee728>:0x0000000ac5ce98>):
    118: 	end	
    119:   end
    120: end %>
    121: <%= render_full_width_custom_fields_rows(@issue) %>
    122: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
    123: </div>
    124: 
  plugins/redmine_workflow_hidden_fields/app/views/issues/show.html.erb:121:in `_494688b6fab6999650dae9d6c5880600'
  plugins/redmine_spent_time_in_issue_description/lib/issues_controller_patch.rb:36:in `block (2 levels) in show_with_plugin'
  plugins/redmine_spent_time_in_issue_description/lib/issues_controller_patch.rb:33:in `show_with_plugin'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by postmxa** [comment]
same here.
Started GET "/issues/86" for XXXXX at 2020-03-30 14:51:28 +0200
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"86"}
  Current user: muuser (id=5)
  Rendering plugins/redmine_workflow_hidden_fields/app/views/issues/show.html.erb within layouts/base
  Rendered issues/_action_menu.html.erb (10.3ms)
  Rendered plugins/redmine_workflow_hidden_fields/app/views/issues/show.html.erb within layouts/base (289.1ms)
Completed 500 Internal Server Error in 647ms (ActiveRecord: 58.7ms)

ActionView::Template::Error (undefined method `render_half_width_custom_fields_rows' for #<#<Class:0x00007f16f4970b00>:0x00007f16f5523128>
Did you mean?  render_custom_fields_rows):
    124:     end
    125:   end
    126: end %>
    127: <%= render_half_width_custom_fields_rows(@issue) %>
    128: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
    129: </div>
    130:

plugins/redmine_workflow_hidden_fields/app/views/issues/show.html.erb:127:in `_plugins_redmine_workflow_hidden_fields_app_views_issues_show_html_erb__4076554045837913113_69868290901780'
app/controllers/issues_controller.rb:107:in `block (2 levels) in show'
app/controllers/issues_controller.rb:100:in `show'
plugins/redmine_per_project_formatting/lib/redmine_per_project_formatting/application_controller_patch.rb:24:in `block in change_text_formatting'
plugins/redmine_per_project_formatting/lib/redmine_per_project_formatting/setting_patch.rb:19:in `within_text_formatting'
plugins/redmine_per_project_formatting/lib/redmine_per_project_formatting/application_controller_patch.rb:23:in `change_text_formatting'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by postmxa** [comment]
FIX:

replacing:
<%= render_half_width_custom_fields_rows(@issue) %>
to 
 <%= render_custom_fields_rows(@issue) %>
in show.html.erb file
fixed problem for me, but I'm not ruby or ROR person so..

diff show.html.erb show.html.erb.old
127c127
< <%= render_custom_fields_rows(@issue) %>
---
> <%= render_half_width_custom_fields_rows(@issue) %>
150c150
< <%= render_custom_fields_rows(@issue) %>
---
> <%= render_full_width_custom_fields_rows(@issue) %>

**Comment by tianyang-abc** [comment]
> FIX:
> 
> replacing:
> `<%= render_half_width_custom_fields_rows(@issue) %>`
> to
> ` <%= render_custom_fields_rows(@issue) %>`
> in show.html.erb file
> fixed problem for me, but I'm not ruby or ROR person so..
> 
> ```
> diff show.html.erb show.html.erb.old
> 127c127
> < <%= render_custom_fields_rows(@issue) %>
> ---
> > <%= render_half_width_custom_fields_rows(@issue) %>
> 150c150
> < <%= render_custom_fields_rows(@issue) %>
> ---
> > <%= render_full_width_custom_fields_rows(@issue) %>
> ```

I'm with Redmine 4.1.1.stable. But @postmxa your patch doesn't work for me. 
production.log as following.

Started GET "/redmine/issues/1" for 192.168.228.1 at 2020-11-17 06:40:08 -0500
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"1"}
  Current user: tianyang (id=1)
[ActiveJob] [ActionMailer::DeliveryJob] [7f67b618-b3bd-4de9-8980-48177b892718]   Rendering mailer/issue_add.text.erb within layouts/mailer
[ActiveJob] [ActionMailer::DeliveryJob] [7f67b618-b3bd-4de9-8980-48177b892718]   Rendered mailer/_issue.text.erb (62.7ms)
[ActiveJob] [ActionMailer::DeliveryJob] [7f67b618-b3bd-4de9-8980-48177b892718]   Rendered mailer/issue_add.text.erb within layouts/mailer (73.6ms)
  Rendering plugins/redmine_workflow_hidden_fields/app/views/issues/show.html.erb within layouts/base
[ActiveJob] [ActionMailer::DeliveryJob] [7f67b618-b3bd-4de9-8980-48177b892718]   Rendering mailer/issue_add.html.erb within layouts/mailer
  Rendered issues/_action_menu.html.erb (31.8ms)
[ActiveJob] [ActionMailer::DeliveryJob] [7f67b618-b3bd-4de9-8980-48177b892718]   Rendered mailer/_issue.html.erb (12.0ms)
[ActiveJob] [ActionMailer::DeliveryJob] [7f67b618-b3bd-4de9-8980-48177b892718]   Rendered mailer/issue_add.html.erb within layouts/mailer (22.4ms)
[ActiveJob] [ActionMailer::DeliveryJob] [7f67b618-b3bd-4de9-8980-48177b892718] Performed ActionMailer::DeliveryJob (Job ID: 7f67b618-b3bd-4de9-8980-48177b892718) from Async(mailers) in 337.15ms
  Rendered plugins/redmine_workflow_hidden_fields/app/views/issues/show.html.erb within layouts/base (543.5ms)
Completed 500 Internal Server Error in 790ms (ActiveRecord: 180.7ms)
  
ActionView::Template::Error (undefined method `render_custom_fields_rows' for #<#<Class:0x0000558ce284ff70>:0x00007efc71f61390>
Did you mean?  render_custom_fields_tabs
               render_custom_field_values):
    124:     end	
    125:   end
    126: end %>
    127: <%= render_custom_fields_rows(@issue) %>
    128: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
    129: </div>
    130: 
  
plugins/redmine_workflow_hidden_fields/app/views/issues/show.html.erb:127:in `_plugins_redmine_workflow_hidden_fields_app_views_issues_show_html_erb___3438983621892484326_69811354385320'
app/controllers/issues_controller.rb:107:in `block (2 levels) in show'
app/controllers/issues_controller.rb:99:in `show'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
