### ISSUE TITLE
Error 500 when open a issue was closed and created from a risks Plugin (not Redmine based issue)

### ISSUE THREAD

**Issue by vvbasti** [alexwais/redmine_workflow_hidden_fields#40]
Rendered plugins/redmine_risks/app/views/risks/_relations.html.erb (8.6ms)
  Rendered plugins/redmine_risks/app/views/risks/_history.html.erb (3.4ms)
  Rendered plugins/redmine_risks/app/views/risks/show.html.erb within layouts/base (26.4ms)
Completed 500 Internal Server Error in 45ms (ActiveRecord: 4.6ms)

ActionView::Template::Error (undefined method `hidden_attribute?' for nil:NilClass):
    10: 
    11:         <% if journal.details.any? %>
    12:           <ul class="details">
    13:             <% details_to_strings(journal.visible_details).each do |string| %>
    14:               <li><%= string %></li>
    15:             <% end %>
    16:           </ul>
  plugins/redmine_workflow_hidden_fields/lib/redmine_workflow_hidden_fields/issues_helper_patch.rb:40:in `block in details_to_strings_with_hidden'
  plugins/redmine_workflow_hidden_fields/lib/redmine_workflow_hidden_fields/issues_helper_patch.rb:39:in `each'
  plugins/redmine_workflow_hidden_fields/lib/redmine_workflow_hidden_fields/issues_helper_patch.rb:39:in `details_to_strings_with_hidden'
  plugins/redmine_risks/app/views/risks/_history.html.erb:13:in `block in _9ef1c303fa0425365436bdfd48e1e896'
  plugins/redmine_risks/app/views/risks/_history.html.erb:3:in `each'
  plugins/redmine_risks/app/views/risks/_history.html.erb:3:in `_9ef1c303fa0425365436bdfd48e1e896'
  plugins/redmine_risks/app/views/risks/show.html.erb:80:in `_82a18f886499e53960e08226d9362e00'
  plugins/redmine_risks/app/controllers/risks_controller.rb:75:in `block (2 levels) in show'
  plugins/redmine_risks/app/controllers/risks_controller.rb:73:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by dzzrit** [comment]
I have also encountered this issue, redmine 5.0. x
Has anyone solved this problem?
